INSERT INTO tbOrdersStatus (ID,Name) VALUES (1,'Pendente');
INSERT INTO tbOrdersStatus (ID,Name) VALUES (2,'Em Analise');
INSERT INTO tbOrdersStatus (ID,Name) VALUES (3,'Confirmado');
INSERT INTO tbOrdersStatus (ID,Name) VALUES (4,'Cancelado');
INSERT INTO tbQuestionnairesRequestsStatus (ID,Name) VALUES (1,'Requested');
INSERT INTO tbQuestionnairesRequestsStatus (ID,Name) VALUES (2,'In Progress');
INSERT INTO tbQuestionnairesRequestsStatus (ID,Name) VALUES (3,'Cancelled');
INSERT INTO tbQuestionnairesRequestsStatus (ID,Name) VALUES (4,'Completed');
INSERT INTO tbTreatmentsPhases (ID,Name) VALUES (1,N'Pre-Tratamento');
INSERT INTO tbTreatmentsPhases (ID,Name) VALUES (2,'Tratamento');
INSERT INTO tbTreatmentsPhases (ID,Name) VALUES (3,N'Pos-Tratamento');
INSERT INTO tbQuestionnairesAnswersTypes (ID,Name) VALUES (1,'Sim/Nao');
INSERT INTO tbQuestionnairesAnswersTypes (ID,Name) VALUES (2,'Texto');
INSERT INTO tbQuestionnairesAnswers (ID,Answer,Value,AnswerType) VALUES (1,'Sim',1,1);
INSERT INTO tbQuestionnairesAnswers (ID,Answer,Value,AnswerType) VALUES (2,'Nao',0,1);
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (1,'Questionario Kappasiniano de Sugestibilidade 1','QSK 1','Responda Sim ou Nao');
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (2,'Questionario Kappasiniano de Sugestibilidade 2','QSK 2','Responda Sim ou Nao');
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (3,'Questionario Kappasiniano de Sexualidade Masculina 1','QSXKM 1','Responda Sim ou Nao');
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (4,'Questionario Kappasiniano de Sexualidade Masculina 2','QSXKM 2','Responda Sim ou Nao');
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (5,'Questionario Kappasiniano de Sexualidade Feminina 1','QSXKF 1','Responda Sim ou Nao');
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (6,'Questionario Kappasiniano de Sexualidade Feminina 2','QSXKF 2','Responda Sim ou Nao');
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (7,'Questionario de Analise de Bem-Estar Geral','QABEG','Responda Sim ou Nao');
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (8,'Questionario de Diagnostico Holistico','QDH','Responda Sim ou Nao');
INSERT INTO tbQuestionnaires (ID,Name,ShortName,Description) VALUES (9,'Questionario de Analise de Qualidade do Sono','QAQS','Responda Sim ou Nao');
INSERT INTO tbProducts (ID,Name,NormalPrice,PromotionalPrice) VALUES (1,'10 Sessoes - 4 Meses',24990,19990);
INSERT INTO tbProducts (ID,Name,NormalPrice,PromotionalPrice) VALUES (2,'20 Sessoes - 8 Meses',39990,29990);
INSERT INTO tbProducts (ID,Name,NormalPrice,PromotionalPrice) VALUES (3,'30 Sessoes - 12 Meses',49990,39990);
INSERT INTO tbFormasPagamento (ID,Name) VALUES (4,'Cartao de Credito - Cielo');
INSERT INTO tbFormasPagamento (ID,Name) VALUES (6,'Boleto Bancario - Banco Inter');
PRINT 'All seed data inserted';
